import Head from 'next/head';
import React, { Fragment } from 'react';

const Dashboard = () => {
    return (
        <Fragment>
            <Head>
                <title>Dashboard | Plagiarism</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            Dashboard
        </Fragment>
    );
}

export default Dashboard;
